import React, { useCallback, useEffect, useRef, useState } from 'react';
import api from './api';

const LABELS = {
  infographic: 'Infographic',
  diagram: 'Diagram',
  illustration: 'Illustration',
};

/**
 * Offers a visual explanation after an assistant turn, and renders it if the
 * user accepts.
 *
 * Two-step by design. Proposing is a cheap text call; rendering costs real
 * money for illustrations. More importantly, a visual that appears uninvited on
 * every turn becomes something users learn to scroll past — the offer only
 * means anything if it's occasional.
 *
 * @param {Array}  messages  [{role, content}] — the conversation so far.
 * @param {boolean} enabled  Set false while the assistant is still streaming.
 */
export default function VisualExplainer({ messages, enabled = true }) {
  const [proposal, setProposal] = useState(null);
  const [dismissed, setDismissed] = useState(false);
  const [visual, setVisual] = useState(null);
  const [rendering, setRendering] = useState(false);
  const [error, setError] = useState(null);

  // Identifies the turn this proposal belongs to, so a late response from a
  // previous turn can't attach itself to the current one.
  const turnKey = messages.length;
  const turnRef = useRef(turnKey);
  turnRef.current = turnKey;

  useEffect(() => {
    setProposal(null);
    setVisual(null);
    setError(null);
    setDismissed(false);

    if (!enabled || messages.length === 0) return undefined;
    if (messages[messages.length - 1].role !== 'assistant') return undefined;

    const controller = new AbortController();
    const forTurn = turnKey;

    api
      .post('/api/visuals/propose', { messages }, { signal: controller.signal })
      .then(({ data }) => {
        if (turnRef.current !== forTurn) return;
        if (data.should_offer) setProposal(data);
      })
      .catch(() => {
        // A failed proposal is a non-event: the chat is complete without it.
      });

    return () => controller.abort();
  }, [turnKey, enabled]);

  const accept = useCallback(() => {
    if (!proposal) return;
    setRendering(true);
    setError(null);

    api
      .post('/api/visuals/render', {
        messages,
        asset_type: proposal.asset_type,
        subject: proposal.subject,
        title: proposal.title,
      })
      .then(({ data }) => {
        setVisual(data);
        setRendering(false);
      })
      .catch((err) => {
        setError(err.response?.data?.detail || err.message);
        setRendering(false);
      });
  }, [proposal, messages]);

  if (visual) return <VisualCard visual={visual} />;

  if (rendering) {
    return (
      <div className="visual-offer visual-offer-busy">
        <span className="visual-spinner" aria-hidden="true" />
        Building your {LABELS[proposal?.asset_type]?.toLowerCase() || 'visual'}…
      </div>
    );
  }

  if (error) {
    return (
      <div className="visual-offer visual-offer-error">
        Couldn't build that visual: {error}
      </div>
    );
  }

  if (!proposal || dismissed) return null;

  return (
    <div className="visual-offer">
      <span className="visual-offer-badge">{LABELS[proposal.asset_type]}</span>
      <span className="visual-offer-pitch">{proposal.pitch}</span>
      <button type="button" className="visual-offer-yes" onClick={accept}>
        Show me
      </button>
      <button
        type="button"
        className="visual-offer-no"
        onClick={() => setDismissed(true)}
        aria-label="Dismiss"
      >
        ✕
      </button>
    </div>
  );
}

/**
 * Renders whichever of the three asset types came back.
 *
 * SVG arrives as markup and is injected directly — it's generated by our own
 * renderer from a validated schema, never passed through from a model, and
 * every string in it is escaped at generation time. Illustrations arrive as
 * base64 image bytes.
 */
export function VisualCard({ visual }) {
  const [zoomed, setZoomed] = useState(false);

  const download = () => {
    const isSvg = visual.format === 'svg';
    const href = isSvg
      ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(visual.content)}`
      : `data:${visual.mime_type};base64,${visual.content}`;
    const link = document.createElement('a');
    link.href = href;
    link.download = `${(visual.title || 'visual').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.${isSvg ? 'svg' : 'png'}`;
    link.click();
  };

  return (
    <figure className={`visual-card${zoomed ? ' visual-card-zoomed' : ''}`}>
      <figcaption className="visual-card-head">
        <span className="visual-card-title">{visual.title}</span>
        <span className="visual-card-actions">
          <button type="button" onClick={() => setZoomed((z) => !z)}>
            {zoomed ? 'Fit' : 'Expand'}
          </button>
          <button type="button" onClick={download}>Download</button>
        </span>
      </figcaption>

      <div className="visual-card-body">
        {visual.format === 'svg' ? (
          <div
            className="visual-svg"
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: visual.content }}
          />
        ) : (
          <img
            className="visual-img"
            src={`data:${visual.mime_type};base64,${visual.content}`}
            alt={visual.title}
          />
        )}
      </div>

      {visual.asset_type === 'illustration' && (
        // Illustrations are model-generated pixels, not data. Saying so keeps
        // anyone from reading meaning into details that are decorative.
        <p className="visual-card-note">AI-generated illustration — conceptual, not to scale.</p>
      )}
    </figure>
  );
}