import os
from langchain_google_community import VertexAISearchRetriever
from langchain_google_vertexai import ChatVertexAI
from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

def generate_agent_builder_response(user_query: str) -> dict:
    """
    Queries Vertex AI Search Agent Builder API, retrieves grounded data chunks, 
    and uses Gemini to construct a formatted, cited technical summary.
    """
    # Target configurations
    PROJECT_ID = "sprinternship-chi1-2026"
    LOCATION_ID = "global"  # Or your specific data store region (e.g. 'us')
    
    # PASTE YOUR DATA STORE ID GENERATED BY THE DATA TEAM HERE:
    DATA_STORE_ID = "your-vertex-data-store-id" 

    # 1. Initialize the live platform retriever API
    # Pass a list of data store IDs to retrieve updates AND how-to guides at the same time
    retriever = VertexAISearchRetriever(
        project_id=PROJECT_ID,
        location_id=LOCATION_ID,
        # Simply list both data store IDs here!
        data_store_ids=[
            "your-release-notes-data-store-id",
            "gcp-official-documentation-data-store-id"
        ],
        get_extractive_answers=True,
        max_documents=5
    )
    
    # 2. Initialize the generation LLM
    llm = ChatVertexAI(
        model="gemini-2.5-flash",
        project=PROJECT_ID,
        location="us-central1",
        temperature=0.2
    )
    
    # 3. Formulate the system instructions
    system_prompt = (
        "You are an expert Google Cloud Solutions Architect.\n"
        "Synthesize complex, technical documentation details into highly actionable answers.\n\n"
        "Instructions:\n"
        "- Format your response with clean Markdown headers: ### Executive Summary, ### Key Details, etc.\n"
        "- Base your response ONLY on the provided context. Do not make up facts.\n\n"
        "Context:\n"
        "{context}"
    )
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])
    
    # 4. Assemble and execute the RAG chain
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    rag_chain = create_retrieval_chain(retriever, question_answer_chain)
    
    print(f"📡 Querying Vertex AI Search App API for: '{user_query}'...")
    response = rag_chain.invoke({"input": user_query})
    
    return {
        "answer": response["answer"],
        "source_documents": response.get("context", [])
    }